# Generated by Django 4.2 on 2023-04-27 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('calendar_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('editable_by', models.ManyToManyField(related_name='editable_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visible_for', models.ManyToManyField(related_name='visible_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('P', 'Praca'), ('D', 'Obowiązki domowe'), ('O', 'Sprawy osobiste'), ('S', 'Spotkanie')], default='P', max_length=1)),
                ('calendar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soocalendar.calendar')),
            ],
        ),
    ]
