# Generated by Django 4.2 on 2023-04-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soocalendar', '0003_rename_start_date_event_beggining_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='calendar_id',
            new_name='calendar',
        ),
    ]
